version: '3.8'

services:
  php-api:
    build:
      context: .
      dockerfile: php.Dockerfile
      args:
        GITHUB_TOKEN: "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"
        CACHEBUST: "${CACHEBUST:-$(date +%s)}"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - php-data:/app/data
    environment:
      DB_PATH: /app/data/jackpot.db

  websocket:
    build:
      context: .
      dockerfile: node.Dockerfile
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    ports:
      - "8080:8080"
      - "4000:4000"
    restart: always
    depends_on:
      - php-api

volumes:
  php-data: